networks:
  itmo:

volumes:
  db_data:

services:
  user-service:
    build:
      context: ./
      dockerfile: ./user-service/Dockerfile
    networks:
      - itmo
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  point-service:
    build:
      context: ./
      dockerfile: ./point-service/Dockerfile
    networks:
      - itmo
    ports:
      - "7070:7070"
    depends_on:
      - user-service

  #  db:
  #    image: container-registry.oracle.com/database/free:latest
  #    environment:
  #      ORACLE_PWD: password
  #      ORACLE_SID: FREE
  #      ORACLE_CHARACTERSET: AL32UTF8
  #    networks:
  #      - itmo
  #    healthcheck:
  #      test: [ "CMD", "sqlplus", "-s", "sys/password@FREE as sysdba", "SELECT 1 FROM dual" ]
  #      interval: 5s
  #      timeout: 5s
  #      retries: 20

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web4
    networks:
      - itmo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d web4" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - itmo
    depends_on:
      - user-service
      - point-service